// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fonipsfmywlsrnlyiduf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvbmlwc2ZteXdsc3JubHlpZHVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MDk2OTksImV4cCI6MjA1Nzk4NTY5OX0.GNrpUbjKHTYEtedrbY60ODL13zRgv1xhxC-922vgHCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);